services:
  cache:
    image: valkey/valkey:9.0.1
    volumes:
    - redis-data:/data
    command: [redis-server, --save, '60', '1', --loglevel, warning]
    restart: always
    read_only: true
  database:
    image: postgres:18-alpine
    volumes:
    - postgres-data:/var/lib/postgresql
    env_file:
    - ./environment
    restart: always
  weblate:
    build:
      context: ./weblate
      dockerfile: Dockerfile
    depends_on:
    - cache
    - database
    volumes:
    - weblate-data:/app/data
    - weblate-cache:/app/cache
    env_file:
    - ./environment
    restart: always
    read_only: true
    tmpfs:
    - /run
    - /tmp
  textlint:
    build:
      context: ./textlint-server
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: ./textlint-server/textlint
      target: /app/textlint
    env_file:
      - ./environment
volumes:
  weblate-cache: {}
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
